name             'butler'
maintainer       'Alexandru Rosianu'
maintainer_email 'rosian_alex@yahoo.com'
license          'All rights reserved'
description      'Installs/Configures Butler'
long_description 'Installs/Configures Butler'
version          '0.1.0'
